"""
report_formatter.py
-------------------
وحدة تنسيق التقارير اليومية بصيغتين:
1. Markdown: مناسب للحفظ المحلي ونسخ الاحتياطي
2. HTML: نسخة أنيقة تُحفظ محلياً (RTL للعربية / LTR للإنجليزية)
3. Telegram MarkdownV2: نص منسّق متوافق مع Telegram API

- يدعم ثنائي اللغة: "Arabic" / "English" / "both" (تقرير عربي + إنجليزي معاً)
- يدعم تقسيم الرسائل الطويلة إلى أجزاء (Telegram حدّه 4096 رمز)
- يولّد مقدمة تحليلية من LLM بلغتين عند تفعيل both
"""

import logging
import os
import re
from datetime import datetime

from llm_summarizer import LLMSummarizer, summarize_all

logger = logging.getLogger(__name__)

MD_DAY_NAMES = {
    0: "الإثنين", 1: "الثلاثاء", 2: "الأربعاء", 3: "الخميس",
    4: "الجمعة", 5: "السبت", 6: "الأحد",
}

EN_DAY_NAMES = {
    0: "Monday", 1: "Tuesday", 2: "Wednesday", 3: "Thursday",
    4: "Friday", 5: "Saturday", 6: "Sunday",
}


def escape_md_v2(text: str) -> str:
    """تهريب الرموز الخاصة بصيغة MarkdownV2 في Telegram."""
    special = r"([_*\[\]()~`>#+\-=|{}.!\\])"
    return re.sub(special, r"\\\1", text)


def _summary_text(summary, lang: str) -> str:
    """استخراج نص الملخص (قد يكون قاموساً عند both)."""
    if isinstance(summary, dict):
        return summary.get(lang, "No summary available")
    return summary or "No summary available"


def _arabic_summary_text(summary) -> str:
    if isinstance(summary, dict):
        return summary.get("Arabic", "لا يوجد ملخص")
    return summary or "لا يوجد ملخص"


def _english_summary_text(summary) -> str:
    if isinstance(summary, dict):
        return summary.get("English", "No summary available")
    return summary or "No summary available"


# ============================================================
# بناء التقرير بصيغة Markdown القياسية (للحفظ المحلي)
# ============================================================

def build_report_markdown(articles: list[dict], intro: str | dict,
                          date: str = None, language: str = "Arabic") -> str:
    """بناء التقرير بصيغة Markdown القياسية. intro قد يكون نصاً أو قاموساً لغتين."""
    date = date or datetime.now().strftime("%Y-%m-%d")
    lines = []

    if language == "both":
        intro_ar = intro.get("Arabic", "") if isinstance(intro, dict) else intro
        intro_en = intro.get("English", "") if isinstance(intro, dict) else intro
        lines.extend([
            f"# 📰 Daily Tech Report — التقرير التقني اليومي | {date}",
            "",
            "## 🌟 Today's Highlights — أبرز ما اليوم",
            "",
            f"{intro_en}",
            "",
            "---",
            "",
            f"{intro_ar}",
            "",
            "==============================",
            "",
        ])
    else:
        intro_text = intro if isinstance(intro, str) else ""
        lines.extend([
            "# 📰 Daily Tech Report" if language == "English" else "# 📰 التقرير التقني اليومي",
            "",
        ])
        if intro_text:
            lines.extend([f"## 🌟 Today's Highlights" if language == "English" else "## 🌟 أبرز ما اليوم", "", intro_text, ""])

    # تجميع حسب المصدر
    by_source = {}
    for a in articles:
        by_source.setdefault(a["source"], []).append(a)

    title = ("## 📚 Articles" if language == "English" else "## 📚 المقالات") + f" ({len(articles)})"
    lines.append(title)
    lines.append("")

    for source, items in by_source.items():
        lines.append(f"### 📌 {source}")
        lines.append("")
        for a in items:
            summary = a.get("summary", "")
            if language == "both" and isinstance(summary, dict):
                lines.append(f"**{a['title']}**")
                lines.append("")
                lines.append(f"🇸🇦 {_arabic_summary_text(summary)}")
                lines.append("")
                lines.append(f"🇬🇧 {_english_summary_text(summary)}")
                lines.append("")
                lines.append(f"🔗 [Read/اقرأ]({a['link']})")
                lines.append("")
            elif language == "English":
                lines.append(f"**{a['title']}**")
                lines.append("")
                lines.append(_english_summary_text(summary))
                lines.append("")
                lines.append(f"🔗 [Read article]({a['link']})")
                lines.append("")
            else:
                lines.append(f"**{a['title']}**")
                lines.append("")
                lines.append(_arabic_summary_text(summary))
                lines.append("")
                lines.append(f"🔗 [اقرأ المقال]({a['link']})")
                lines.append("")
        lines.append("")

    if language == "both":
        lines.extend([
            "---",
            f"*Auto-generated by Tech News AI Agent | تم إنشاء هذا التقرير تلقائياً — {datetime.now():%Y-%m-%d %H:%M}*",
        ])
    elif language == "English":
        lines.extend([
            "---",
            f"*Auto-generated by Tech News AI Agent — {datetime.now():%Y-%m-%d %H:%M}*",
        ])
    else:
        lines.extend([
            "---",
            f"*تم إنشاء هذا التقرير تلقائياً بواسطة Tech News AI Agent — {datetime.now():%Y-%m-%d %H:%M}*",
        ])
    return "\n".join(lines)


def build_report_telegram(articles: list[dict], intro: str | dict,
                          date: str = None, language: str = "Arabic") -> list[str]:
    """
    بناء نص التقرير بصيغة Telegram MarkdownV2.
    يعيد قائمة أجزاء، كل جزء ≤ 4096 رمز (حد Telegram).
    """
    date = date or datetime.now().strftime("%Y-%m-%d")
    weekday = datetime.now().weekday()

    parts: list[str] = []

    if language == "both":
        intro_ar = intro.get("Arabic", "") if isinstance(intro, dict) else intro
        intro_en = intro.get("English", "") if isinstance(intro, dict) else intro
        header = (
            f"📰 *Daily Tech Report — التقرير التقني اليومي* 📰\n\n"
            f"📅 {date} | {EN_DAY_NAMES.get(weekday)} — {MD_DAY_NAMES.get(weekday)}\n\n"
            f"🌟 *Today's Highlights / أبرز ما اليوم*\n{intro_en}\n\n─────────────────\n\n{intro_ar}\n"
            f"\n📊 Articles/المقالات: {len(articles)}\n"
            "─────────────────\n"
        )
    elif language == "English":
        header = (
            f"📰 *Daily Tech Report* 📰\n\n"
            f"📅 {date} ({EN_DAY_NAMES.get(weekday)})\n\n"
            f"📊 Articles: {len(articles)}\n"
            "─────────────────\n"
        )
        if isinstance(intro, dict):
            intro = intro.get("English", "")
        if intro:
            header += f"🌟 *Today's Highlights*\n{intro}\n\n─────────────────\n"
    else:
        header = (
            f"📰 *التقرير التقني اليومي* 📰\n\n"
            f"📅 {date} ({MD_DAY_NAMES.get(weekday)})\n\n"
            f"📊 عدد المقالات: {len(articles)}\n"
            "─────────────────\n"
        )
        if isinstance(intro, dict):
            intro = intro.get("Arabic", "")
        if intro:
            header += f"🌟 *أبرز ما اليوم*\n{intro}\n\n─────────────────\n"

    parts.append(header)

    for a in articles:
        summary = a.get("summary", "")
        if language == "both" and isinstance(summary, dict):
            entry = (
                f"📌 *{escape_md_v2(a['title'])}*\n"
                f"🇸🇦 {_arabic_summary_text(summary)}\n"
                f"🇬🇧 {_english_summary_text(summary)}\n"
                f"🔗 {escape_md_v2(a['link'])}\n"
            )
        elif language == "English":
            entry = (
                f"📌 *{escape_md_v2(a['title'])}*\n"
                f"📝 {_english_summary_text(summary)}\n"
                f"🔗 {escape_md_v2(a['link'])}\n"
            )
        else:
            entry = (
                f"📌 *{escape_md_v2(a['title'])}*\n"
                f"📝 {_arabic_summary_text(summary)}\n"
                f"🔗 {escape_md_v2(a['link'])}\n"
            )
        parts.append(entry)

    if language == "both":
        footer = "\n─────────────────\n_Auto-generated by Tech News AI Agent 🤖_ | _تم الإنشاء بواسطة Tech News AI Agent 🤖_"
    elif language == "English":
        footer = "\n─────────────────\n_Auto-generated by Tech News AI Agent 🤖_"
    else:
        footer = "\n─────────────────\n_تم الإنشاء بواسطة Tech News AI Agent 🤖_"
    parts.append(footer)

    # دمج الأجزاء مع احترام حد 4096
    MAX_LEN = 4000  # هامش أمان
    merged = []
    current = ""
    for part in parts:
        if len(current) + len(part) + 2 > MAX_LEN and current:
            merged.append(current)
            current = part
        else:
            current += part + "\n"
    if current:
        merged.append(current)
    return merged


def save_report(md_text: str, language: str, config: dict,
                  articles: list[dict] = None, intro: str | dict = None) -> dict:
    """حفظ التقرير بصيغتي Markdown وHTML محلياً.
    عند اللغة both يُنشأ ملفان منفصلان: تقرير عربي (RTL) وتقرير إنجليزي (LTR)."""
    output_cfg = config.get("output", {})
    date = datetime.now().strftime("%Y-%m-%d")
    results = {}
    os.makedirs("reports", exist_ok=True)

    if language == "both":
        suffixes = {"Arabic": "_ar", "English": "_en"}
    else:
        suffixes = {language: ""}

    for lang, suffix in suffixes.items():
        # بناء نسخة أحادية اللغة نظيفة للعرض المحلي
        if articles:
            lang_md = build_report_markdown(articles, intro or "", date, lang)
        else:
            lang_md = md_text

        # عند الوضع الأحادي: حفظ باسم عام report_{date}.md (بدون لاحقة)
        # وعند both: حفظ بنسخ منفصلة _ar و _en
        filename_md = f"reports/report_{date}{suffix}.md"
        filename_html = f"reports/report_{date}{suffix}.html"

        if output_cfg.get("save_local_md", True):
            with open(filename_md, "w", encoding="utf-8") as f:
                f.write(lang_md)
            results["md_" + lang] = filename_md

        if output_cfg.get("save_local_html", True):
            html = _md_to_html(lang_md, date, rtl=(lang == "Arabic"))
            with open(filename_html, "w", encoding="utf-8") as f:
                f.write(html)
            results["html_" + lang] = filename_html

    return results


def _md_to_html(md_text: str, date: str, rtl: bool = True) -> str:
    """تحويل بسيط من Markdown إلى HTML مع تصميم أنيق (RTL/LTR)."""
    body = md_text
    # تحويلات البلوكات أولاً (قبل التغليف داخل <p>)
    body = re.sub(r"^# (.+)$", r"<h1>\1</h1>", body, flags=re.M)
    body = re.sub(r"^## (.+)$", r"<h2>\1</h2>", body, flags=re.M)
    body = re.sub(r"^### (.+)$", r"<h3>\1</h3>", body, flags=re.M)
    body = re.sub(r"^---$", "<hr>", body, flags=re.M)
    body = re.sub(r"^─+$", "", body, flags=re.M)
    # تحويلات السطور داخل الفقرات
    body = re.sub(r"^\*\*(.+)\*\*$", r"<strong>\1</strong>", body, flags=re.M)
    body = re.sub(r"^\[(.+)\]\((.+)\)$", r'<a href="\2">\1</a>', body, flags=re.M)
    body = re.sub(r"^\*(.+)\*$", r"<em>\1</em>", body, flags=re.M)

    def _wrap_line(line: str) -> str:
        stripped = line.strip()
        if not stripped:
            return "<br>"
        if stripped.startswith("<h") or stripped.startswith("<hr"):
            return stripped
        return f"<p>{stripped}</p>"
    paragraphs = [_wrap_line(line) for line in body.split("\n")]
    body_html = "\n".join(paragraphs)

    dir_attr = 'dir="rtl"' if rtl else 'dir="ltr"'
    lang_attr = 'lang="ar"' if rtl else 'lang="en"'

    return f"""<!DOCTYPE html>
<html {lang_attr} {dir_attr}>
<head>
<meta charset="utf-8">
<title>Daily Tech Report — {date}</title>
<style>
  body {{
    font-family: 'Segoe UI', Tahoma, sans-serif;
    max-width: 800px; margin: 30px auto; padding: 20px;
    background: #f7f9fc; color: #1f2937; line-height: 1.8;
  }}
  h1 {{ color: #0f172a; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }}
  h2 {{ color: #1d4ed8; margin-top: 30px; }}
  h3 {{ color: #4338ca; background: #eef2ff; padding: 8px 12px; border-radius: 8px; }}
  a {{ color: #2563eb; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  hr {{ border: none; border-top: 2px dashed #cbd5e1; margin: 25px 0; }}
  strong {{ color: #0f172a; }}
</style>
</head>
<body>
{body_html}
</body>
</html>"""


def generate_full_report(config: dict, articles: list[dict]) -> dict:
    """الدالة الرئيسية: توليد التقرير الكامل (ملخصات + مقدمة + تنسيق + حفظ)."""
    language = config.get("language", "both")
    summarizer = LLMSummarizer(config["llm"], language=language)

    if not articles:
        if language == "both":
            md_text = ("# 📰 Daily Tech Report — التقرير التقني اليومي\n\n"
                       "⚠️ No new articles matched today's keywords.\n"
                       "⚠️ لا توجد مقالات جديدة ضمن الكلمات المفتاحية المحددة اليوم.")
            tg_parts = [md_text]
        elif language == "English":
            md_text = "# 📰 Daily Tech Report\n\n⚠️ No new articles matched today's keywords."
            tg_parts = [md_text]
        else:
            md_text = "# 📰 التقرير التقني اليومي\n\n⚠️ لا توجد مقالات جديدة ضمن الكلمات المفتاحية المحددة اليوم."
            tg_parts = [md_text]
        return {"md": md_text, "telegram": tg_parts, "files": {}, "intro": ""}

    # تلخيص المقالات (باللغة المحددة)
    articles = summarize_all(summarizer, articles)

    # توليد المقدمة التحليلية
    intro = ""
    try:
        intro = summarizer.generate_report_intro(articles)
    except Exception as e:
        logger.warning(f"Failed to generate intro: {e}")
        if language == "both":
            intro = {
                "English": f"{len(articles)} articles collected from the specified sources today.",
                "Arabic": f"تم جمع {len(articles)} مقالة تقنية من المصادر المحددة اليوم.",
            }
        elif language == "English":
            intro = f"{len(articles)} articles collected from the specified sources today."
        else:
            intro = f"تم جمع {len(articles)} مقالة تقنية من المصادر المحددة اليوم."

    date = datetime.now().strftime("%Y-%m-%d")
    md_text = build_report_markdown(articles, intro, date, language)
    tg_parts = build_report_telegram(articles, intro, date, language)
    files = save_report(md_text, language, config, articles, intro)

    return {"md": md_text, "telegram": tg_parts, "files": files, "intro": intro}
